pip install boto
pip install pystmark
pip install cheetah
pip install pymongo
pip install cherrypy
pip install flask
pip install flask-wtf
pip install pycrypto
pip install pyDes
pip install twilio
pip install nexmo
pip install pillow
pip install py4j
pip install crc16
pip install pdfkit
pip install delorean
pip install M2Crypto
pip install Crypto
pip install Mongothon
pip install pusher
